# NBA Simulator - Simple Model
### Author: Patrick de Guzman
### Data source: [Basketball Reference](https://www.basketball-reference.com/)

## Loading Required Packages
```{r}
if(!require(readxl)){
    install.packages("readxl")
    library(readxl)
}

if(!require(data.table)){
    install.packages("data.table")
    library(data.table)
}

if(!require(rlang)){
      install.packages("rlang")
      library(rlang)
}

if(!require(readr)){
      install.packages("readr")
      library(readr)
}
```

## Loading & Processing Data 
```{r}
GameStatSequence <- list.files("./Team Data/Team by Season by Game Stats")
OppGameStatSequence <- list.files("./Team Data/Team by Season by Opp Game Stats")
AdvStatSequence <- list.files("./Team Data/Team by Season by Advanced")

TeamData <- data.frame()

for(i in seq_along(GameStatSequence)){
      file <- GameStatSequence[i]
      path <- paste0("./Team Data/Team by Season by Game Stats/",file)
      data <- read_xls(path, skip = 1)
      rbind(TeamData,data)
}
```